version: '3'
services:
  nest:
    build:
      context: .  
    ports:
      - 3001:3001  
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017  
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:

# networks:
#   my-network:

networks: 
  default: 
    external: 
      name: network-stack